# Auto-generated by scripts/update-versions.sh
# Run: ./scripts/update-versions.sh
# Runs as part of `hmu`
{
  claude-code = {
    version = "2.1.31";
    sha256 = "sha256-CZmwSrVjNDxWrBuMM1knrqs+o0AtW9heBh5uDLMibCY=";
  };

  opencode = {
    version = "1.1.51";
    sha256 = "sha256-0GdT7AnTSgl43Knxu52CewAQIspO+vx1GCKBO2Q/T/k=";
  };

  pi = {
    version = "0.51.6";
    sha256 = "sha256-rY9BCcKxpAs/GJ8BIznG0aK7/LpR2bIK/ol/XUg/Crk=";
  };
}
