# Auto-generated by scripts/update-versions.sh
# Run: ./scripts/update-versions.sh
# Runs as part of 
{
  claude-code = {
    version = "2.1.42";
    sha256 = "sha256-WnXQcTKHtjZjagbOkQP/VPV4gXDy6TEvx1WRIfZJ028=";
  };

  opencode = {
    version = "1.2.0";
    sha256 = "sha256-uAyVeInW7264ekPaglBEe3RUmyKdqHa0J7YY+JN/SwY=";
  };

  pi = {
    version = "0.52.12";
    sha256 = "sha256-I/fyhD1hQ1jTn00U5Q0AwPdy+c6DgBTEcrTEa87zxPY=";
  };
}
