# Auto-generated by scripts/update-versions.sh
# Run: ./scripts/update-versions.sh
# Runs as part of hmu
{
  claude-code = {
    version = "2.1.209";
    sha256 = "sha256-J4y2jvchfPzFyUnSVzu45ZqLEwX3Zon7qI63IrDZ4vA=";
  };

  opencode = {
    version = "1.17.20";
    sha256 = "sha256-CkFXLoOolusAhoNYnf4J4XuUHQYSJghRDz5fFthtmvw=";
  };

  pi = {
    version = "0.80.6";
    sha256 = "sha256-DiJ3MYciNn/mhGn9Hq/b9c0oVvgWP9bLHwjwBGeAhNU=";
  };
}
