#!/usr/bin/env bash
set -euo pipefail

# Output file for versions
VERSIONS_FILE="$(dirname "$0")/../versions.nix"

# Read current versions from versions.nix if it exists
get_current_version() {
  local name="$1"
  if [ -f "$VERSIONS_FILE" ]; then
    grep -A1 "^  $name = {" "$VERSIONS_FILE" | grep 'version' | sed 's/.*"\(.*\)".*/\1/' || echo ""
  else
    echo ""
  fi
}

get_current_sha256() {
  local name="$1"
  if [ -f "$VERSIONS_FILE" ]; then
    grep -A2 "^  $name = {" "$VERSIONS_FILE" | grep 'sha256' | sed 's/.*"\(sha256-[^"]*\)".*/\1/' || echo ""
  else
    echo ""
  fi
}

# Get fetchzip hash by intentionally failing with wrong hash and extracting the correct one
get_fetchzip_hash() {
  local url="$1"
  nix-build --no-out-link -E "
    with import <nixpkgs> {};
    fetchzip {
      url = \"$url\";
      sha256 = \"sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\";
      stripRoot = false;
    }
  " 2>&1 | grep "got:" | awk '{print $2}' || echo ""
}

CURRENT_CLAUDE=$(get_current_version "claude-code")
CURRENT_OPENCODE=$(get_current_version "opencode")
CURRENT_PI=$(get_current_version "pi")

echo "Checking for updates..."

# Claude Code
echo -n "  claude-code: "
CLAUDE_GCS="https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases"
CLAUDE_VERSION=$(curl -sL "$CLAUDE_GCS/latest")
if [ "$CLAUDE_VERSION" = "$CURRENT_CLAUDE" ]; then
  echo "$CLAUDE_VERSION (up to date)"
  CLAUDE_SRI=$(get_current_sha256 "claude-code")
  UPDATED_CLAUDE=false
else
  echo "$CURRENT_CLAUDE -> $CLAUDE_VERSION (updating...)"
  CLAUDE_URL="$CLAUDE_GCS/$CLAUDE_VERSION/linux-arm64/claude"
  CLAUDE_SHA256=$(nix-prefetch-url "$CLAUDE_URL" 2>/dev/null)
  CLAUDE_SRI=$(nix hash to-sri --type sha256 "$CLAUDE_SHA256" 2>/dev/null)
  UPDATED_CLAUDE=true
fi

# OpenCode
echo -n "  opencode: "
OPENCODE_VERSION=$(curl -s https://api.github.com/repos/anomalyco/opencode/releases/latest | jq -r '.tag_name' | sed 's/^v//')
if [ "$OPENCODE_VERSION" = "$CURRENT_OPENCODE" ]; then
  echo "$OPENCODE_VERSION (up to date)"
  OPENCODE_SRI=$(get_current_sha256 "opencode")
  UPDATED_OPENCODE=false
else
  echo "$CURRENT_OPENCODE -> $OPENCODE_VERSION (updating...)"
  OPENCODE_URL="https://github.com/anomalyco/opencode/releases/download/v${OPENCODE_VERSION}/opencode-linux-arm64.tar.gz"
  OPENCODE_SHA256=$(nix-prefetch-url "$OPENCODE_URL" 2>/dev/null)
  OPENCODE_SRI=$(nix hash to-sri --type sha256 "$OPENCODE_SHA256" 2>/dev/null)
  UPDATED_OPENCODE=true
fi

# Pi
echo -n "  pi: "
PI_VERSION=$(curl -s https://api.github.com/repos/badlogic/pi-mono/releases/latest | jq -r '.tag_name' | sed 's/^v//')
if [ "$PI_VERSION" = "$CURRENT_PI" ]; then
  echo "$PI_VERSION (up to date)"
  PI_SRI=$(get_current_sha256 "pi")
  UPDATED_PI=false
else
  echo "$CURRENT_PI -> $PI_VERSION (updating...)"
  PI_URL="https://github.com/badlogic/pi-mono/releases/download/v${PI_VERSION}/pi-linux-arm64.tar.gz"
  PI_SRI=$(get_fetchzip_hash "$PI_URL")
  UPDATED_PI=true
fi

# Check if any updates needed
if [ "$UPDATED_CLAUDE" = false ] && [ "$UPDATED_OPENCODE" = false ] && [ "$UPDATED_PI" = false ]; then
  echo ""
  echo "All packages are up to date!"
  exit 0
fi

# Write versions.nix
cat > "$VERSIONS_FILE" << EOF
# Auto-generated by scripts/update-versions.sh
# Run: ./scripts/update-versions.sh
# Runs as part of `hmu`
{
  claude-code = {
    version = "$CLAUDE_VERSION";
    sha256 = "$CLAUDE_SRI";
  };

  opencode = {
    version = "$OPENCODE_VERSION";
    sha256 = "$OPENCODE_SRI";
  };

  pi = {
    version = "$PI_VERSION";
    sha256 = "$PI_SRI";
  };
}
EOF

echo ""
echo "Updated $VERSIONS_FILE"
